---
name: "ListenBrainz"
guid: "59B20823-AAFE-454C-A393-17427F518631"
version: "3.1.0.1"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Track your music habits with ListenBrainz."
description: >
  A plugin to send your music listening activity on Jellyfin to ListenBrainz.
category: "General"
owner: "lyarenei"
artifacts:
  - "Jellyfin.Plugin.ListenBrainz.dll"
  - "Jellyfin.Plugin.ListenBrainz.Http.dll"
  - "Jellyfin.Plugin.ListenBrainz.Api.dll"
  - "Jellyfin.Plugin.ListenBrainz.MusicBrainzApi.dll"
changelog: >
  New:
    - Select which libraries to exclude from submitting listens (#41 @lyarenei)
  Maintenance:
    - Improvements to submit and resubmit process (#46 @Maxr1998)
