---
name: "ListenBrainz"
guid: "59B20823-AAFE-454C-A393-17427F518631"
version: "3.3.2.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Track your music habits with ListenBrainz."
description: >
  A plugin to send your music listening activity on Jellyfin to ListenBrainz.
category: "General"
owner: "lyarenei"
artifacts:
  - "Jellyfin.Plugin.ListenBrainz.dll"
  - "Jellyfin.Plugin.ListenBrainz.Http.dll"
  - "Jellyfin.Plugin.ListenBrainz.Api.dll"
  - "Jellyfin.Plugin.ListenBrainz.MusicBrainzApi.dll"
changelog: >
  Fix
    - Various fixes for listens cache (#68 @lyarenei)
    - Fix error propagation, so listen cache works as intended (#73 @lyarenei)
