---
name: "ListenBrainz"
guid: "59B20823-AAFE-454C-A393-17427F518631"
version: "2.3.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Track your music habits with ListenBrainz."
description: >
  A plugin to send your music listening activity on Jellyfin to ListenBrainz.
category: "General"
owner: "lyarenei"
artifacts:
  - "Jellyfin.Plugin.Listenbrainz.dll"
  - "Jellyfin.Plugin.Listenbrainz.MusicBrainz.dll"
  - "Jellyfin.Plugin.Listenbrainz.Http.dll"
changelog: >
  Re-release on new repo
