name: Bug Report
description: Report an issue in the plugin.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please take your time to fill out this bug report, thank you.
        Reports filled with obvious little to no effort are likely to be closed without further comments.
  - type: textarea
    id: what-happened
    attributes:
      label: Bug description
      description: A clear and concise description of what is not working.
      placeholder: It worked before and now it's broken.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug.
      placeholder: |
        1. Do something
        2. Wait for '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should happen if the feature worked correctly?
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What happens instead?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Copy and paste any relevant log output here.
        Please make sure to enable debug logging as there will be much more information available.
        Also please check out the Debug logging section in README on how to properly set up debug logging for the plugin.
      render: shell
  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description: What plugin version do you have currently installed?
      placeholder: 3.x.y.z
    validations:
      required: true
  - type: input
    id: jellyfin-version
    attributes:
      label: Jellyfin Version
      description: What Jellyfin version are you running?
      placeholder: 10.a.b
    validations:
      required: true
  - type: textarea
    id: additional-ctx
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the bug.
