name: Feature request
description: Suggest a new feature or an improvement for the plugin.
title: "[Request]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of your suggestion.
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Proposed solution
      description: Describe possible solution(s).
  - type: textarea
    id: additional-ctx
    attributes:
      label: Additional context
      description: Add any other context or screenshots which would help to better illustrate or further clarify your idea.
