name: 'Build Plugin'

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: Determine version
        shell: bash
        run: nbgv get-version

      - name: Build plugin
        run: dotnet publish -c Release

      - name: Collect plugin binaries
        run: |
          mkdir -p /home/runner/work/plugin-binaries/10-7
          mkdir -p /home/runner/work/plugin-binaries/10-8
          pushd /home/runner/work/jellyfin-plugin-listenbrainz/jellyfin-plugin-listenbrainz/Jellyfin.Plugin.Listenbrainz/bin/Release/net5.0 && \
          cp Jellyfin.Plugin.Listenbrainz.dll /home/runner/work/plugin-binaries/10-7 && \
          popd
          pushd /home/runner/work/jellyfin-plugin-listenbrainz/jellyfin-plugin-listenbrainz/Jellyfin.Plugin.Listenbrainz.JF108/bin/Release/net6.0 && \
          cp Jellyfin.Plugin.Listenbrainz.dll /home/runner/work/plugin-binaries/10-8 && \
          popd

      - name: Upload built binaries
        uses: actions/upload-artifact@v3
        with:
          name: plugin_binaries
          retention-days: 14
          if-no-files-found: error
          path: /home/runner/work/plugin-binaries
