# $schema: https://json.schemastore.org/github-workflow
name: 'Build and release plugin'

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  test:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/test.yaml@master
    with:
      dotnet-version: "8.0"

  build:
    needs: test
    uses: .github/workflows/build.yml@main

  upload:
    needs: build
    uses: .github/workflows/upload.yml@main

  upload-repo:
    needs: build
    uses: .github/workflows/upload-repo.yml@main
    with:
      repo: "jellyfin"
    secrets:
      host: ${{ secrets.DEPLOY_HOST }}
      username: ${{ secrets.DEPLOY_USER }}
      key: ${{ secrets.DEPLOY_KEY }}

  publish:
    if: ${{ contains(github.repository, 'lyarenei/') }}
    needs: upload
    uses: .github/workflows/publish.yml@main
    with:
      repo: "jellyfin"
    secrets:
      host: ${{ secrets.DEPLOY_HOST }}
      username: ${{ secrets.DEPLOY_USER }}
      key: ${{ secrets.DEPLOY_KEY }}
