name: 'Build Plugin'

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # tag=v2.1.0
        with:
          dotnet-version: "6.0.x"

      - name: Build plugin
        run: dotnet publish -c Release

      - name: Create ZIP archive for JF 10.7
        run: |
          pushd /home/runner/work/jellyfin-plugin-listenbrainz/jellyfin-plugin-listenbrainz/Jellyfin.Plugin.Listenbrainz/bin/Release/net5.0 && \
          zip "/home/runner/work/jellyfin_plugin_listenbrainz_jf7.zip" Jellyfin.Plugin.Listenbrainz.dll && \
          popd

      - name: Create ZIP archive for JF 10.8
        run: |
          pushd /home/runner/work/jellyfin-plugin-listenbrainz/jellyfin-plugin-listenbrainz/Jellyfin.Plugin.Listenbrainz.JF8/bin/Release/net6.0 && \
          zip "/home/runner/work/jellyfin_plugin_listenbrainz_jf8.zip" Jellyfin.Plugin.Listenbrainz.dll && \
          popd

      - name: Upload plugin zip for JF 10.7
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: build-artifact
          retention-days: 14
          if-no-files-found: error
          path: "/home/runner/work/jellyfin_plugin_listenbrainz_jf7.zip"

      - name: Upload plugin zip for JF 10.8
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: build-artifact
          retention-days: 14
          if-no-files-found: error
          path: "/home/runner/work/jellyfin_plugin_listenbrainz_jf8.zip"
