name: 'Publish Plugin (dev)'

on: { }

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      MANIFEST_FILE: "/var/www/repos/jellyfin-dev/manifest.json"
      REPO_PATH: "/var/www/repos/jellyfin-dev"
      REPO_URL: "https://repo.xkrivo.net/jellyfin-dev"
    steps:
      - name: Update Plugin Manifest
        uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262 # v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          envs: MANIFEST_FILE,REPO_PATH,REPO_URL
          script: |-
            lockfile="/run/lock/jprm.lock"
            pushd "${REPO_PATH}/${{ github.repository }}/${{ inputs.version }}" || exit 1
            (
                flock -x 300
                python3.9 -m jprm --verbosity=debug repo add --url="${REPO_URL}" "${MANIFEST_FILE}" ./*.zip || exit 1
            ) 300>${lockfile}
            popd || exit 1
            rm -r "${REPO_PATH}/${{ github.repository }}/${{ inputs.version }}" || exit 1
