name: Release plugin for JF 10.7

on:
  push:
    tags:
      - '1.[0-9]+.[0-9]+'
jobs:
  build:
    name: Build & create release
    runs-on: ubuntu-latest

    steps:
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName

      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # tag=v2.1.0
        with:
          dotnet-version: "6.0.x"

      - name: Build plugin
        run: dotnet publish -c Release

      - name: Create ZIP archive for JF 10.7
        run: |
          pushd /home/runner/work/jellyfin-plugin-listenbrainz/jellyfin-plugin-listenbrainz/Jellyfin.Plugin.Listenbrainz/bin/Release/net5.0 && \
          zip "/home/runner/work/jellyfin_plugin_listenbrainz_jf107.zip" Jellyfin.Plugin.Listenbrainz.dll && \
          popd

      - name: Create github release and attach plugin
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "/home/runner/work/jellyfin_plugin_listenbrainz_jf107.zip"
          asset_name: "jellyfin_plugin_listenbrainz_${{ steps.tagName.outputs.tag }}.zip"
          tag: ${{ github.ref }}
          overwrite: true
          body: "This release was created by bot; no changelog available."
