name: 'Test Plugin'

on:
  push:
    branches:
      - 10.8.x-compat
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    branches:
      - 10.8.x-compat
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/test.yaml@master
